baseURL = 'https://blog.brennenputh.me/'
languageCode = 'en-us'
title = '''Brennen's Blog'''
theme        = "hugo-kiera"

pygmentsCodeFences = true

[author]
    name = "Brennen Puth"           #Author name
    github = "brennenputh"         #Github username

[params]
    tagline = ""
    customCSS = []  #Optional Customised CSS
    disableDarkModeCSS = false # disables css style for users using dark-mode
